### ISSUE TITLE
Can't parse ES2020

### ISSUE THREAD

**Issue by falsandtru** [unassert-js/unassert#21]
Could you support ES2021?

```console
Message:
    Unknown node type ChainExpression.
Details:
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: Unknown node type ChainExpression.
    at Controller.replace (...\node_modules\estraverse\estraverse.js:608:27)
    at Object.replace (...\node_modules\estraverse\estraverse.js:651:27)
    at unassert (...\node_modules\unassert\index.js:120:23)
    at applyUnassertWithoutSourceMap (...\node_modules\gulp-unassert\index.js:74:29)
    at transform (...\node_modules\gulp-unassert\index.js:81:33)
    at DestroyableTransform._transform (...\node_modules\gulp-unassert\index.js:92:9)
    at DestroyableTransform.Transform._read (...\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (...\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (...\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (...\node_modules\readable-stream\lib\_stream_writable.js:417:5)
```

**Comment by twada** [comment]
Okay I'll work on it. This will take a while.

**Comment by twada** [comment]
I'll working on this and it may contain some little breaking changes, but most of users does not get affected.
